# Generated by Django 5.0.3 on 2024-03-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
    ]
