# Generated by Django 5.0.3 on 2024-03-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0003_employee_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
