# Generated by Django 5.0.3 on 2024-03-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0004_alter_employee_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='pub_date',
        ),
    ]
