# Generated by Django 5.0.3 on 2024-03-08 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0005_remove_employee_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
