# Generated by Django 5.0.3 on 2024-03-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0006_employee_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
